### ISSUE TITLE
Error when running extract.sh

### ISSUE THREAD

**Issue by InferiousDeveloper** [Jacxk/all-spigot-nms#6]
Extracting all spigot.jar files, please wait...
Currently extracting ../spigot_versions/spigot-1.10.2-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.11.2.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.12.2.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.13.2.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.13.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.14.4.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.15.2.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.16.1.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.16.3.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.16.5.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.17.1.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.18.1.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.8-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.8.3-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.9.2-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Currently extracting ../spigot_versions/spigot-1.9.4-R0.1-SNAPSHOT-latest.jar...
./extract.sh: line 26: jar: command not found
./extract.sh: line 27: jar: command not found
./extract.sh: line 28: jar: command not found
Extraction completed!

This is what's firing after I download the jar files.

**Comment by BlackBaroness** [comment]
Maybe you dont have java installed
